version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Install Phase
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*.hmtl"
    - "**/*.js"
    - "**/*.css"
    - "**/*.ico"
    - "**/*.json"
  discard-paths: yes
  base-directory: "dist/angular-d3"
