version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Install Phase
      - apt-get update
      - npm install -g @angular/cli
  pre_build:
    commands:
      - npm install
  build:
    commands:
#      - npm run build
      - ng build --prod --aot
  post_build:
    commands:
#      - echo Post Build Phase
      - aws s3 sync ./dist/dice-q4-okr s3://mmenard-dhi-okr-host-prod --delete

artifacts:
  files:
    - "**/*.hmtl"
    - "**/*.js"
    - "**/*.css"
    - "**/*.ico"
    - "**/*.json"
  discard-paths: yes
  base-directory: "dist/dice-q4-okr"
