version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build --prod
  post_build:
    commands:
      - aws s3 sync ./dist/angular-d3 s3://mmenard-angular-devops-prod --acl 'public-read' --delete
# artifacts:
#   files:
#     - "assets/*.json"
#     - "**/*.hmtl"
#     - "**/*.js"
#     - "**/*.css"
#     - "**/*.ico"
#   discard-paths: yes
#   base-directory: "dist/angular-d3"
